//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agenda.Service.Factories {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SkeletonAgendaFactoryResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SkeletonAgendaFactoryResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Agenda.Service.Factories.SkeletonAgendaFactoryResource", typeof(SkeletonAgendaFactoryResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions arising from the minutes that are not on the agenda.
        /// </summary>
        internal static string ActionsArising {
            get {
                return ResourceManager.GetString("ActionsArising", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any other business.
        /// </summary>
        internal static string AnyOtherBusiness {
            get {
                return ResourceManager.GetString("AnyOtherBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apologies.
        /// </summary>
        internal static string Apologies {
            get {
                return ResourceManager.GetString("Apologies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval of minutes of the previous meeting.
        /// </summary>
        internal static string ApproveMinutes {
            get {
                return ResourceManager.GetString("ApproveMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of next meeting.
        /// </summary>
        internal static string DateNextMeeting {
            get {
                return ResourceManager.GetString("DateNextMeeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matters arising that are not on the agenda.
        /// </summary>
        internal static string MattersArising {
            get {
                return ResourceManager.GetString("MattersArising", resourceCulture);
            }
        }
    }
}
